### ISSUE TITLE
Conduct Sep 1st- 3rd compensation request voting

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#107]
_(previous voting round: #94 )_

 - [x] Announce call for requests 3 days ahead and provide instructions on how to submit in a comment on this issue
 - [x] Transcribe [compensation requests](https://github.com/bisq-network/compensation/issues) to [stake and voting spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=912569327)
 - [x] Announce that the voting period has begun in a comment on this issue (also: created Slack reminder)
 - [x] Wait for the voting period to complete
 - [x] Review all edits to the spreadsheet to ensure there weren't any mistakes, etc
 - [x] Protect this month's spreadsheet worksheet such that only the @bisq-network/compensation-maintainers can edit it
 - [x] Announce that the voting period is complete in a comment below (see prior months' voting epics for examples)
 - [x] Close all related compensation request issues with a comment  (see prior months' compensation requests for examples)
 - [x] Complete any tasks in the comments below

**Comment by ripcurlx** [comment]
@bisq-network/contributors, please submit any compensation requests by EOD on Friday August 31st.

As usual, instructions can be found at https://docs.bisq.network/dao/phase-zero.html#how-to-request-compensation. Thanks.

**Comment by ripcurlx** [comment]
Compensation requests have been staged in the BSQ stake and vote tracking spreadsheet, and the voting period is now open.

The specific worksheet for this month is at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=693056200

Voting instructions are at https://docs.bisq.network/dao/phase-zero.html#how-to-vote.

Some of you will be voting for the first time and will need access. Just request it and I'll grant it.

Please don't forget that we are voting this time again based on the [Natural delegation on DAO voting proposal](https://github.com/bisq-network/proposals/issues/34). Only vote `+1` on compensation requests you can evaluate and do know about, for all other compensation requests vote `0` to show your intention to delegate your vote.

Please complete your voting by EOD on Monday September 3rd.

Thanks all.
