### ISSUE TITLE
Conduct Dec 1st–4th compensation request voting

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#165]
_(previous voting round: #149 )_

 - [x] Announce call for requests 3 days ahead and provide instructions on how to submit in a comment on this issue
 - [x] Announce that the review period (1st) has begun in a comment on this issue
 - [x] Transcribe [compensation requests](https://github.com/bisq-network/compensation/issues) to [stake and voting spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=912569327)
 - [x] Announce that the voting period (2nd - 4th) has begun in a comment on this issue (also: created Slack reminder)
 - [x] Wait for the voting period to complete
 - [x] Review all edits to the spreadsheet to ensure there weren't any mistakes, etc
 - [x] Protect this month's spreadsheet worksheet such that only the @bisq-network/compensation-maintainers can edit it
 - [x] Announce that the voting period is complete in a comment below (see prior months' voting epics for examples)
 - [x] Close all related compensation request issues with a comment  (see prior months' compensation requests for examples)
 - [x] Complete any tasks in the comments below

**Comment by ripcurlx** [comment]
@bisq-network/contributors, please submit any compensation requests by EOD on Friday November 30th.

As usual, instructions can be found at https://docs.bisq.network/dao/phase-zero.html#how-to-request-compensation. Thanks.

To match the setup of the Bisq DAO on Testnet, we'll have an additional review day on December 1st and the voting takes place from 2nd to 4th of December.

**Comment by ripcurlx** [comment]
As we try to mimic the process on Testnet more closely, we'll have an additional review phase this month. All compensation requests that will be added to the voting spreadsheet end of today are already assigned to the corresponding contributor. Please review and comment if necessary on the compensation requests today. Thanks!

**Comment by ripcurlx** [comment]
Being in the process of transcribing this month's compensation request, I found out that on Nov 2017 @Nolaan and @eyalron33 had an accepted compensation request, but never received the BSQ amount, because of an error in the formula. I'll change their account balance in this months voting spreadsheet.

**Comment by Technohacker** [comment]
@ripcurlx I would like to add that my compensation request was accepted, but by BSQ balance wasn't updated, as well.

**Comment by rex4539** [comment]
@ripcurlx I never checked before but I also just noticed missing BSQ on my address.

https://github.com/bisq-network/compensation/issues/78
https://github.com/bisq-network/compensation/issues/106

Based on the above compensation requests, I should have 1580 BSQ (excluding this month's request) but the spreadsheet shows 1540 BSQ.

Analyzing the spreadsheet, it appears that on the first request I was credited 1330 BSQ instead of 1370 BSQ.

**Comment by ripcurlx** [comment]
@Technohacker I just checked the spreadsheet and you got the 30 BSQ you requested. If you look at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=2089071698 at your address it says 30 in the column `balance before vote`

**Comment by ripcurlx** [comment]
@rex4539 I just checked your compensation request #78 and it is correct that it says 1370 now. You edited the value on the 1st of June from 1330 to 1370 when voting took place already and no changes were allowed anymore. Can you please add this contribution to next month voting again?

**Comment by Technohacker** [comment]
@ripcurlx Oh. My Bisq balance didn't update I guess

**Comment by ripcurlx** [comment]
@Technohacker You mean in the Bisq client? There you'll only see a BSQ balance as soon as it is live on Mainnet. Until then your balance is only visible in the spreadsheet right now.

**Comment by ripcurlx** [comment]
@bisq-network/contributors Compensation requests have been staged in the BSQ stake and vote tracking spreadsheet, and the voting period is now open.

The specific worksheet for this month is at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=722083962

Voting instructions are at https://docs.bisq.network/dao/phase-zero.html#how-to-vote.

Some of you will be voting for the first time and will need access. Just request it and I'll grant it.

Please don't forget that we are voting this time again based on the [Natural delegation on DAO voting proposal](https://github.com/bisq-network/proposals/issues/34). Only vote `+1` on compensation requests you can evaluate and do know about, for all other compensation requests vote `0` to show your intention to delegate your vote.

Please complete your voting by EOD on Friday November 4th.

Thanks all.

**Comment by cbeams** [comment]
Correction:

> Please complete your voting by EOD on Friday November 4th

should have read "... by EOD on **Tuesday December 4th**".

**Comment by ripcurlx** [comment]
@cbeams Thanks - shouldn't work too early in the morning ;-)

**Comment by eyalron33** [comment]
@ripcurlx thanks for updating! I didn't notice that my previous request (for 2000 BSQ) was accepted, and now I updated it, with Manfred's advice, to also include this month (so another 2000 BSQ).

Will the other 2000 BSQ will be voted?

**Comment by ripcurlx** [comment]
@eyalron33 Sorry for replying that late. We had an intense crunch time to release the new version. I transcribed the 4000 BSQ from your compensation request. So it is actually 2000 BSQ? In that case I could update the value down, as people who voted might not change their mind if you want less.

**Comment by ripcurlx** [comment]
@bisq-network/contributors The new release is out and now is time for voting! You still can vote today until EOD!

**Comment by eyalron33** [comment]
@ripcurlx No, I asked for 4000 BSQ. I was just didn't sure what you transcribed. Sorry.

**Comment by ripcurlx** [comment]
Compensation Voting Complete

This voting period is now complete, and the results are as follows:

18 contributors submitted 18 compensation requests.
Two first-time compensation requests this time (Welcome @aejontargaryen and @pedromvpg  👍).
7 stakeholders voted.

Total compensation requested was 174,087 BSQ.
Total compensation received was 174,087 BSQ.

This time the BSQ received was an unusual high amount, as two big features (Redesign, BSQ DAO) were submitted for compensation.

We have now completed 14 monthly voting rounds. In total, we have approved the creation of 721,574 new BSQ, or roughly 52,000 BSQ per month on average.

Everyone who got compensated please contact @cbeams, so you’re added to the GitHub organization. Thanks!

**Comment by ripcurlx** [comment]
Closing as complete.
