### ISSUE TITLE
Conduct Jan 1st–4th compensation request voting

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#183]
_(previous voting round: #165 )_

 - [x] Announce call for requests 3 days ahead and provide instructions on how to submit in a comment on this issue
 - [x] Announce that the review period (1st) has begun in a comment on this issue
 - [x] Transcribe [compensation requests](https://github.com/bisq-network/compensation/issues) to [stake and voting spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1002567596)
 - [x] Announce that the voting period (2nd - 4th) has begun in a comment on this issue (also: created Slack reminder)
 - [x] Wait for the voting period to complete
 - [x] Review all edits to the spreadsheet to ensure there weren't any mistakes, etc
 - [x] Protect this month's spreadsheet worksheet such that only the @bisq-network/compensation-maintainers can edit it
 - [ ] Announce that the voting period is complete in a comment below (see prior months' voting epics for examples)
 - [ ] Close all related compensation request issues with a comment  (see prior months' compensation requests for examples)
 - [ ] Complete any tasks in the comments below

**Comment by ripcurlx** [comment]
@bisq-network/contributors, please submit any compensation requests by EOD on Monday December 31st.

As usual, instructions can be found at https://docs.bisq.network/dao/phase-zero.html#how-to-request-compensation. Thanks.

To match the setup of the Bisq DAO on Testnet, we'll have an additional review day on January 1st and the voting takes place from 2nd to 4th of January.

Please also add your compensation request within the Bisq DAO Testnet in one of the next voting cycles for testing [1]. Thanks, Merry Christmas and a Happy New Year!

[1] [Instructional video](https://www.youtube.com/watch?v=OdoXsSqinQM) on how to file a compensation request in the Bisq DAO.

**Comment by ripcurlx** [comment]
Happy New Year 2019! 🎆 🍾 Like last month, we have an additional review phase this month. All compensation requests that will be added to the voting spreadsheet end of today are already assigned to the corresponding contributor and moved to discussion. Please review and comment if necessary on the compensation requests today. Thanks!

**Comment by ripcurlx** [comment]
@bisq-network/contributors Compensation requests have been staged in the BSQ stake and vote tracking spreadsheet, and the voting period is now open.

The specific worksheet for this month is at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1002567596

Voting instructions are at https://docs.bisq.network/dao/phase-zero.html#how-to-vote.

Some of you will be voting for the first time and will need access. Just request it and I'll grant it.

Please don't forget that we are voting this time again based on the [Natural delegation on DAO voting proposal](https://github.com/bisq-network/proposals/issues/34). Only vote `+1` on compensation requests you can evaluate and do know about, for all other compensation requests vote `0` to show your intention to delegate your vote.

Please complete your voting by EOD on Friday January 4th.

Thanks all.

**Comment by ripcurlx** [comment]
Compensation Voting Complete

This voting period is now complete, and the results are as follows:

15 contributors submitted 15 compensation requests.
Two first-time compensation requests this time (Welcome @initCCG and @ CaveSpectre11  👍).
7 stakeholders voted.

Total compensation requested was 48,685 BSQ.
Total compensation received was 48,685 BSQ.

We have now completed 15 monthly voting rounds. In total, we have approved the creation of 770,259 new BSQ, or roughly 51,000 BSQ per month on average.

Please file your compensation request again in the client for testing after the next update (v0.9.2 - currently there is an issue on Testnet) [1]. Thanks!

Everyone who got compensated please contact @ManfredKarrer, so you’re added to the GitHub organization. Thanks!

[1] Instructional video on how to file a compensation request in the Bisq DAO.

**Comment by ripcurlx** [comment]
Closing as complete.
