### ISSUE TITLE
Conduct Feb 1st–4th compensation request voting

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#204]
_(previous voting round: #183 )_

 - [x] Announce call for requests 3 days ahead and provide instructions on how to submit in a comment on this issue
 - [x] Announce that the review period (1st) has begun in a comment on this issue
 - [x] Transcribe [compensation requests](https://github.com/bisq-network/compensation/issues) to [stake and voting spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=476879080)
 - [x] Announce that the voting period (2nd - 4th) has begun in a comment on this issue (also: created Slack reminder)
 - [x] Wait for the voting period to complete
 - [x] Review all edits to the spreadsheet to ensure there weren't any mistakes, etc
 - [x] Protect this month's spreadsheet worksheet such that only the @bisq-network/compensation-maintainers can edit it
 - [x] Announce that the voting period is complete in a comment below (see prior months' voting epics for examples)
 - [x] Close all related compensation request issues with a comment  (see prior months' compensation requests for examples)
 - [x] Complete any tasks in the comments below

**Comment by ripcurlx** [comment]
@bisq-network/contributors, please submit any compensation requests by EOD on Thursday January 31st.

As usual, instructions can be found at https://docs.bisq.network/dao/phase-zero.html#how-to-request-compensation. Thanks.

To match the setup of the Bisq DAO on Testnet, we'll have an additional review day on February 1st and the voting takes place from 2nd to 4th of February.

Please also add your compensation request within the Bisq DAO Testnet in one of the next voting cycles for testing [1]. Thanks!

[1] [Instructional video](https://www.youtube.com/watch?v=OdoXsSqinQM) on how to file a compensation request in the Bisq DAO.

**Comment by KanoczTomas** [comment]
@ripcurlx the compensation request is greyed out in the testnet DAO. When will the proposal phase be available roughly? Also I assume the BSQ address has to be used from the mainnet DAO as before, right?

**Comment by ripcurlx** [comment]
> @ripcurlx the compensation request is greyed out in the testnet DAO. When will the proposal phase be available roughly? Also I assume the BSQ address has to be used from the mainnet DAO as before, right?
The Bisq DAO Testnet compensation request is just for testing, the real voting will still take place in the spreadsheet. I think the next voting phase on Testnet will start some time tomorrow or the day after (depending on your timezone).

**Comment by ripcurlx** [comment]
@bisq-network/contributors As the proposal phase is active right now on Testnet, please file your compensation requests there as well. You can link your CR also if it is still [WIP], but it would be great if we have a mirror state on Testnet this time and also do the voting in the voting spreadsheet and on Testnet! Thanks!

**Comment by ripcurlx** [comment]
@bisq-network/contributors All compensation requests that will be added to the voting spreadsheet end of today are already assigned to the corresponding contributor and moved to discussion. Please review and comment if necessary on the compensation requests today. Thanks!

**Comment by ripcurlx** [comment]
@bisq-network/contributors Compensation requests have been staged in the BSQ stake and vote tracking spreadsheet, and the voting period is now open.

The specific worksheet for this month is at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=476879080

Voting instructions are at https://docs.bisq.network/dao/phase-zero.html#how-to-vote.

Some of you will be voting for the first time and will need access. Just request it and I'll grant it.

Please don't forget that we are voting this time again based on the [Natural delegation on DAO voting proposal](https://github.com/bisq-network/proposals/issues/34). Only vote `+1` on compensation requests you can evaluate and do know about, for all other compensation requests vote `0` to show your intention to delegate your vote.

Please complete your voting by EOD on Monday February 4th.

Thanks all!

**Comment by ripcurlx** [comment]
Compensation Voting Complete

This voting period is now complete, and the results are as follows:

16 contributors submitted 18 compensation requests.
No first-time compensation requests this time.
7 stakeholders voted.

Total compensation requested was 47,115 BSQ.
Total compensation received was 47,115 BSQ.

We have now completed 16 monthly voting rounds. In total, we have approved the creation of 817,374 new BSQ, or roughly 51,000 BSQ per month on average.

Please file your compensation request again in the client for testing after the next update (v0.9.4) or if you are able to build from master you can do it in 1-2 days time, when the latest fixes are merged [1]. Thanks!

Everyone who got compensated please contact @ManfredKarrer, so you’re added to the GitHub organization. Thanks!

[1] [Instructional video](https://www.youtube.com/watch?v=OdoXsSqinQM) on how to file a compensation request in the Bisq DAO.

**Comment by ripcurlx** [comment]
Closing as complete.
