### ISSUE TITLE
Conduct April 1st-4th compensation request voting

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#243]
_(previous voting round: #222 )_

 - [x] Announce call for requests 3 days ahead and provide instructions on how to submit in a comment on this issue
 - [x] Announce that the review period (1st) has begun in a comment on this issue
 - [x] Transcribe [compensation requests](https://github.com/bisq-network/compensation/issues) to [stake and voting spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=820601546)
 - [x] Announce that the voting period (3rd - 5th) has begun in a comment on this issue (also: created Slack reminder)
 - [x] Wait for the voting period to complete
 - [x] Review all edits to the spreadsheet to ensure there weren't any mistakes, etc
 - [x] Protect this month's spreadsheet worksheet such that only the @bisq-network/compensation-maintainers can edit it
 - [x] Announce that the voting period is complete in a comment below (see prior months' voting epics for examples)
 - [x] Close all related compensation request issues with a comment  (see prior months' compensation requests for examples)
 - [x] Complete any tasks in the comments below

**Comment by ripcurlx** [comment]
@bisq-network/contributors, please submit any compensation requests by EOD on Sunday March 31st.

This might be the last voting round using our Google Spreadsheet, so don't miss out this historic event 😉.

As usual, instructions can be found at https://docs.bisq.network/dao/phase-zero.html#how-to-request-compensation. Thanks.

To match the setup of the Bisq DAO on Testnet, we'll have an additional review day on April 1st and the voting takes place from 2nd to 4th of April.

Please also add your compensation request within the Bisq DAO Testnet in one of the next voting cycles for testing [1]. Thanks!

[1] [Instructional video](https://www.youtube.com/watch?v=OdoXsSqinQM) on how to file a compensation request in the Bisq DAO.

**Comment by flix1** [comment]
Hi @ripcurlx I understand that the addresses listed in the spreadsheet will be abandoned and that we need to submit a new BSQ address from Bisq 0.9.5 client that lists all our past compensations so that the current address balance will be transferred in the DAO genesis distribution. Is this correct?

I have some doubts because I see no similar requests in github/compensation/issues so far...

Also the instructions  (https://docs.bisq.network/compensation.html) give two possible ways to make a compensation request:
-The usual (github)
-An e-mail to genesis@bitsquare.io.

**Comment by ManfredKarrer** [comment]
For the spread sheet we use the old BSQ address. Before I will do the genesis I will request from all contributors the new BSQ address as well.

**Comment by ripcurlx** [comment]
As pointed out by @oscarguindzberg on Slack, the total sum of BSQ added in the voting spreadsheet was incorrect (the last few lines were not included in the sum formular) since 2018.10. Each single compensation requests was not affected by this mistake, only the total reporting.

**e.g. for February 2019:**
Total compensation requested was ~52,050~ 114,070 BSQ.
Total compensation received was ~52,050~ 114,070 BSQ.

We have now completed 17 monthly voting rounds. In total, we have approved the creation of ~869,424~ 1,020,705 new BSQ, or roughly ~51,000~ 60,000 BSQ per month on average.

Here @oscarguindzberg compensation request didn't make it into the sum which causes this big difference. Sorry about this mistake in reporting! Luckily it will be our last voting round within the Google spreadsheet 😄

**Comment by ripcurlx** [comment]
@bisq-network/contributors All compensation requests (we have a new record with 23 CRs 🚀 ) that will be added to the voting spreadsheet end of today are already assigned to the corresponding contributor and moved to discussion. Please review and comment if necessary on the compensation requests today. Thanks!

**Comment by ripcurlx** [comment]
@bisq-network/contributors Thanks everyone who participated in the discussion on the valuation of compensation requests. If someone wants to change the amount or the description of her/his compensation request, feel free to do so until EOD. I'll delay the voting this time for one day, because of the special circumstances.

**Comment by oscarguindzberg** [comment]
@ripcurlx Is there a link to what has been decided about the valuation of compensation requests? I would like to check if I have to adjust mine.

**Comment by ripcurlx** [comment]
> @ripcurlx Is there a link to what has been decided about the valuation of compensation requests? I would like to check if I have to adjust mine.

That's the issue I was referencing: https://github.com/bisq-network/compensation/issues/261

**Comment by ripcurlx** [comment]
@bisq-network/contributors Compensation requests have been staged in the BSQ stake and vote tracking spreadsheet, and the voting period is now open.

The specific worksheet for this month is at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=459254761

Voting instructions are at https://docs.bisq.network/dao/phase-zero.html#how-to-vote.

Some of you will be voting for the first time and will need access. Just request it and I'll grant it.

Please don't forget that we are voting this time again based on the [Natural delegation on DAO voting proposal](https://github.com/bisq-network/proposals/issues/34). Only vote `+1` on compensation requests you can evaluate and do know about, for all other compensation requests vote `0` to show your intention to delegate your vote.

Please complete your voting by EOD on Friday April 5th, as we delayed the voting period for one day.

Thanks all!

**Comment by ripcurlx** [comment]
Compensation Voting Complete

This voting period is now complete, and the results are as follows:

23 contributors submitted 23 compensation requests.
8 first-time compensation requests this time (Welcome @michaltakac, @FKrauss, @y3v63n, @huey735, @Mycelial1, @ben-kaufman, @Wimking1987 and @blabno  👍).
10 stakeholders voted.

Total compensation requested was 136,775 BSQ.
Total compensation received was 136,775 BSQ.

We have now completed 18 monthly voting rounds. In total, we have approved the creation of 1,157,480 new BSQ, or roughly 64,000 BSQ per month on average.

Please file your compensation request again in the client as we have only a couple of test voting cycles left until the Bisq DAO Mainnet launch [1]. Thanks!

Everyone who got compensated please contact @ManfredKarrer, so you’re added to the GitHub organization. Thanks everyone for participating in this last voting round in this way and I'm looking forward to our first Mainnet voting cycle!

[1] [Instructional video](https://www.youtube.com/watch?v=OdoXsSqinQM) on how to file a compensation request in the Bisq DAO.

**Comment by ripcurlx** [comment]
Closing as complete.

@bisq-network/contributors The proposal phase for this voting cycle will end at ~10th of May 10:15 (please check the Bisq client `DAO -> Governance` for exact timing). Please submit your compensation requests as always here on GitHub and reference it in your first Bisq DAO compensation request within the Bisq client. See https://docs.bisq.network/getting-started-dao.html#participate-in-a-voting-cycle for more details.
