### ISSUE TITLE
Conduct Mar 1st–3rd compensation request voting

### ISSUE THREAD

**Issue by cbeams** [bisq-network/compensation#44]
- [x] Announce call for requests 3 days ahead and provide instructions on how to submit
 - [x] Transcribe [compensation requests](https://github.com/bisq-network/compensation/issues) to [stake and voting spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1018906710)
 - [x] Announce that the voting period has begun
 - [x] Wait for the voting period to complete
 - [x] Review all edits to the spreadsheet to ensure there weren't any mistakes, etc
 - [x] Announce that the voting period is complete
 - [x] Close all related compensation request issues
 - [x] Complete any tasks in the comments below
 - [x] Update the phase zero doc if appropriate
 - [x] Write up a post-mortem / retrospective on the mailing list to see what we've learned
  
> _NOTE: starting now, these "conduct voting" issues are being managed here in `compensation`, vs where they were before in `dao`, e.g. bisq-network/dao#39. This makes it simpler to link things, and it better reflects the fact that these voting periods really are compensation request specific. As yet, we've never voted on anything but._

**Comment by cbeams** [comment]
- [ ] When this voting round is complete, communicate to everyone that going forward they should do monthly report comments on the roles they're responsible for, e.g. how @alexej996 did it in https://github.com/bisq-network/roles/issues/19#issuecomment-369414524 and how I've been doing it for the roles I'm responsible for. Compensation requests should be "thin", ideally containing just the following information:
 
1. BSQ requested & BSQ address to send it to
2. Links to monthly update comments for any roles that contributor is assigned to
3. Links to PRs, issues and any other work completed that is not otherwise associated with one of the roles in (2).
4. Any other general notes or context that aren't captured by content at the links in (1) or (2).

**Comment by cbeams** [comment]
- [ ] @cbeams: respond to @csacher's [question in Slack](https://bisq.slack.com/archives/C6YNLRYS2/p1519875788000013) about role specs, and communicate it more broadly to everyone else involved.

![image](https://user-images.githubusercontent.com/301810/36840157-54719446-1d44-11e8-99ab-e17c5fc8abeb.png)

Note that I have been explicitly documenting that no progress has been made with role specs in my monthly Roles Maintainer updates, e.g. https://github.com/bisq-network/roles/issues/28#issuecomment-362119648. But it's good to do something more visible here and communicate what the next steps are. Basically, I think we can relax things a bit; just make sure that issue descriptions are up to date, and that all role assignees do monthly report comments on their roles consistently. That's enough for the moment, and we can start formalizing role specs as necessary in the future. I'd love to have everything properly tracked in Git, but it just hasn't been able to get priority next to everything else.

Same thing with bonding—we may just continue waiting on it at this point, i.e. keep punting until on-chain mechanisms are implemented, instead of burning resources trying to implement it at the spreadsheet level. Not sure; need to talk with @sqrrm and @ManfredKarrer about that.

In any case, it'll be good to get out of this limbo state where everything role has TODOs on it for specs and bonding, but no clear instructions / deadlines or negative consequences for not getting these things taken care of.

**Comment by cbeams** [comment]
The following messages have been sent to the bisq-contrib list:

> On Feb 26, 2018, at 2:39 PM, Chris Beams <chris@beams.io> wrote:
> 
> The next Bisq DAO voting period is March 1st–3rd, three days from now.
> 
> Please submit any compensation requests by EOD on Wednesday, February 28th.
> 
> Instructions are at https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#submit-a-compensation-request
> 
> Thanks,
> 

[...]

**Comment by cbeams** [comment]
> From: Chris Beams <chris@beams.io>
> Subject: Mar 1st–3rd voting period results 
> Date: March 4, 2018 at 2:21:03 PM GMT+1
> To: bisq-contrib@lists.bisq.network
> 
> The Mar 1st–3rd voting period is now complete, and the results are as follows:
> 
> 8 contributors submitted 8 compensation requests during this period.
> 1 of these contributors submitted a request for the first time.
> 
> Total compensation requested was 72,200 BSQ.
> Total compensation received was 46,200 BSQ.
> 
> We have now completed 5 monthly voting rounds. In total, we have approved the creation of 267,750 new BSQ, or roughly 54,000 BSQ per month on average.
> 
> Also note that I’ve added a new “index” page to the spreadsheet to help newcomers navigate a bit more easily. All links from the Phase Zero doc have been updated to point to this new page.
> 
> See https://github.com/bisq-network/compensation/issues/44 for further details.
> 
> Thanks to everyone who contributed and to everyone who voted!
> 
> \- Chris
>
