### ISSUE TITLE
Conduct Apr 4th–6th compensation request voting

### ISSUE THREAD

**Issue by cbeams** [bisq-network/compensation#56]
- [x] Announce call for requests 3 days ahead and provide instructions on how to submit
 - [x] Transcribe [compensation requests](https://github.com/bisq-network/compensation/issues) to [stake and voting spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=912569327)
 - [x] Announce that the voting period has begun
 - [x] Wait for the voting period to complete
 - [x] Review all edits to the spreadsheet to ensure there weren't any mistakes, etc
 - [x] Protect this month's spreadsheet worksheet such that only the @bisq-network/compensation-maintainers can edit it
 - [x] Announce that the voting period is complete on the bisq-contrib mailing list, include results, and paste that message in a comment below
 - [ ] Close all related compensation request issues with a comment
 - [x] Complete any tasks in the comments below
 - [x] Update the phase zero doc if appropriate

**Comment by cbeams** [comment]
@bisq-network/contributors, the voting period is now open, as was just announced on the bisq-contrib list:

> Compensation requests have been staged in the BSQ stake and vote tracking spreadsheet, and the voting period is now open.
> 
> Please complete your voting by EOD on Friday, April 6th.
> 
> The spreadsheet is at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=912569327
> 
> And voting instructions are at 
> https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#vote-on-compensation-requests.
>

**Comment by cbeams** [comment]
> Begin forwarded message:
> 
> From: Chris Beams <chris@beams.io>
> Subject: Apr 4th–6th voting period results
> Date: April 9, 2018 at 2:43:31 PM GMT+2
> To: bisq-contrib@lists.bisq.network
> 
> The Mar 1st–3rd voting period is now complete, and the results are as follows:
> 
> 12 contributors submitted 12 compensation requests during this period.
> 4 of these contributors submitted a request for the first time, all related to BTC/USD liquidity week market-making.
> 
> Total compensation requested was 37,180 BSQ.
> Total compensation received was 37,180 BSQ.
> 
> We have now completed 6 monthly voting rounds. In total, we have approved the creation of 304,930 new BSQ, or roughly 51,000 BSQ per month on average.
> 
> See https://github.com/bisq-network/compensation/issues/56 for further details.
> 
> Thanks to everyone who contributed and to everyone who voted!
> 
> \- Chris
