### ISSUE TITLE
Conduct May 5th–7th compensation request voting

### ISSUE THREAD

**Issue by cbeams** [bisq-network/compensation#58]
_(previous voting round: #56)_

 - [x] Announce call for requests 3 days ahead and provide instructions on how to submit
 - [x] Transcribe [compensation requests](https://github.com/bisq-network/compensation/issues) to [stake and voting spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=912569327)
 - [x] Announce that the voting period has begun
 - [x] Wait for the voting period to complete
 - [x] Review all edits to the spreadsheet to ensure there weren't any mistakes, etc
 - [x] Protect this month's spreadsheet worksheet such that only the @bisq-network/compensation-maintainers can edit it
 - [x] Announce that the voting period is complete ~~on the bisq-contrib mailing list~~, include results, ~~and paste that message~~ in a comment below
 - [ ] Close all related compensation request issues with a comment
 - [x] Complete any tasks in the comments below
 - [x] Update the phase zero doc (and other docs) as appropriate

**Comment by cbeams** [comment]
@bisq-network/contributors, I've just pushed the dates for this month's voting period out by a couple days, from May 1st–3rd to **May 3rd–5th.**

This is for a couple reasons:

1. I didn't announce the call for compensation requests 3 days ahead of time like a usually do, and so I don't want people to feel like they need to scramble to get theirs together on short notice today.

2. I want to give everyone time to review the proposal I put together yesterday at about compensating only _delivered_ work at bisq-network/proposals#19.

So **please submit your compensation requests by EOD on Wednesday May 2nd**, and then we'll have the voting period from the 3rd–5th.

And when you write your request, please keep in mind the proposal that [Primary role owners should write monthly report comments on their respective role issues](https://github.com/bisq-network/proposals/issues/13). That proposal has achieved a rough consensus and I'll be closing it out shortly. Please take a moment to review it once again before writing your own request this month, as it will probably change the way you do things, especially if you play one or more roles under the DAO.

Also, with the proposal to submit compensation requests only for delivered work, some contributors may find that they don't need to submit a request at all this month, or that they have less to submit. Having less paperwork is one of the side effect benefits of that proposal.

As usual, the instructions for submitting a compensation request can be found at https://docs.bisq.network/dao/phase-zero.html#how-to-request-compensation (though note that I'll probably transcribe this into a new, dedicated `Compensation` doc soon under the new docs.bisq.network structure.)

Please give a 👍 to this comment just so I know folks have gotten the communication, thanks.

**Comment by cbeams** [comment]
I am pushing the voting period out yet one day further, such that it runs from May 5th–7th. Once again, my apologies.

Stay tuned for my announcement tomorrow that the spreadsheet is ready to go. Thanks, all.

**Comment by cbeams** [comment]
Compensation requests have been staged in the BSQ stake and vote tracking spreadsheet, and the May 5th-7th voting period is now open.

The spreadsheet is at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1591092247

And voting instructions are at https://docs.bisq.network/dao/phase-zero.html#how-to-vote.

**Please complete your voting by EOD on Monday, May 7th.**

P.S.: Since this is the first time I'm announcing the start of voting solely via GitHub issues (and no longer via the bisq-contrib mailing list), **please react with a 👍 to this comment** even if you don't plan to vote, just so I know people have seen it, thanks!

**Comment by sqrrm** [comment]
Since the github issues show in the slack compensation channel I find it quite easy to follow, anyone interested in compensation would probably look either here or in the slack channel.

**Comment by cbeams** [comment]
This voting period is now complete, and the results are as follows:

9 contributors submitted 9 compensation requests.
0 were first-time compensation requests.
7 stakeholders voted.

Total compensation requested was 24,502 BSQ.
Total compensation received was 24,502 BSQ.

We have now completed 7 monthly voting rounds. In total, we have approved the creation of 329,432 new BSQ, or roughly 47,000 BSQ per month on average.

> NOTE: This month throws off the average above, because this is the first month that we're strictly compensating only _delivered_ work as per https://github.com/bisq-network/proposals/issues/19. We may see more "lumpy" compensation numbers going forward, as some units of work will be delivered at different times than others.

Thanks to everyone who contributed and to everyone who voted!
