### ISSUE TITLE
Conduct Jul 1st- 4th compensation request voting

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#82]
_(previous voting round: #70)_

 - [x] Announce call for requests 3 days ahead and provide instructions on how to submit in a comment on this issue (also: created Slack reminder)
 - [x] Transcribe [compensation requests](https://github.com/bisq-network/compensation/issues) to [stake and voting spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=912569327)
 - [x] Announce that the voting period has begun in a comment on this issue (also: created Slack reminder)
 - [x] Wait for the voting period to complete
 - [x] Review all edits to the spreadsheet to ensure there weren't any mistakes, etc
 - [x] Protect this month's spreadsheet worksheet such that only the @bisq-network/compensation-maintainers can edit it
 - [x] Announce that the voting period is complete in a comment below (see prior months' voting epics for examples)
 - [x] Close all related compensation request issues with a comment  (see prior months' compensation requests for examples)
 - [x] Complete any tasks in the comments below

**Comment by ripcurlx** [comment]
I've added two Slack reminders:

- remind everyone to create compensation requests until the end of each month
```
/remind @channel “The next Bisq DAO voting period is from 1st-3rd next month. Please submit any compensation requests until EOD on the last day of the month. Instructions are at https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#submit-a-compensation-request” on the 25th day of every month at 1pm
```
- remind everyone to vote until the third of each month
```
/remind @channel “All compensation requests have been staged in the BSQ stake and vote tracking spreadsheet, and the voting period is now open. Please complete your voting by EOD on the 3rd of this month. Voting instructions are at https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#vote-on-compensation-requests.” on the 1st day of every month at 10am
```

**Comment by ripcurlx** [comment]
@bisq-network/contributors, please submit any compensation requests by EOD on Saturday June 30th.

As usual, instructions can be found at https://docs.bisq.network/dao/phase-zero.html#how-to-request-compensation. Thanks.

**Comment by ripcurlx** [comment]
Compensation requests have been staged in the BSQ stake and vote tracking spreadsheet, and the voting period is now open.

The specific worksheet for this month is at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1841918998

And voting instructions are at https://docs.bisq.network/dao/phase-zero.html#how-to-vote.

Some of you will be voting for the first time and will need access. Just request it and I'll grant it.

Please complete your voting by EOD on Tuesday July 3rd.

Thanks all.

**Comment by cbeams** [comment]
Great job taking everything over this month, @ripcurlx. Thanks again.

**Comment by ripcurlx** [comment]
Thanks! Now I have one more reason to push @ManfredKarrer to release the DAO asap 😉.
