### ISSUE TITLE
Conduct Aug 1st- 3rd compensation request voting

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#94]
_(previous voting round: #82)_

 - [x] Announce call for requests 3 days ahead and provide instructions on how to submit in a comment on this issue (also: created Slack reminder)
 - [x] Transcribe [compensation requests](https://github.com/bisq-network/compensation/issues) to [stake and voting spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=912569327)
 - [x] Announce that the voting period has begun in a comment on this issue (also: created Slack reminder)
 - [x] Wait for the voting period to complete
 - [x] Review all edits to the spreadsheet to ensure there weren't any mistakes, etc
 - [x] Protect this month's spreadsheet worksheet such that only the @bisq-network/compensation-maintainers can edit it
 - [x] Announce that the voting period is complete in a comment below (see prior months' voting epics for examples)
 - [x] Close all related compensation request issues with a comment  (see prior months' compensation requests for examples)
 - [x] Complete any tasks in the comments below

**Comment by ripcurlx** [comment]
@bisq-network/contributors, please submit any compensation requests by EOD on Tuesday July 31st.

As usual, instructions can be found at https://docs.bisq.network/dao/phase-zero.html#how-to-request-compensation. Thanks.

**Comment by ripcurlx** [comment]
@bisq-network/contributors, as discussed in our first dev call:

> @ManfredKarrer 
 Dao voting: Maybe “do not vote if you don’t know much about the contribution” should become standard recommendation. That everyone validates every contribution will not scale. Natural delegation if only those vote who worked with contributor.

We could try it out in this month's voting for the first time only to vote `+1` on compensation requests we can evaluate and do know about, for all other compensation requests vote `0` to show your intention to delegate your vote. 

We might be able to run a quick voting in a proposal for this. I'll post the link to the proposal as a comment as soon as it is ready for voting.

Also if you don't have access to the voting spreadsheet already and like to vote this month, please send me a DM on Slack with your email to be added.

**Comment by ripcurlx** [comment]
@bisq-network/contributors please have a look and vote for the [Natural delegation on DAO voting propsal](https://github.com/bisq-network/proposals/issues/34) so we have a consensus in time for this month's voting round.

**Comment by ripcurlx** [comment]
Compensation requests have been staged in the BSQ stake and vote tracking spreadsheet, and the voting period is now open.

The specific worksheet for this month is at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=298863945

I had to fix a small issue in the sheet (column BD was skipped in old sheet formulas), which only had an effect if a contributor had a first time contribution within this column.

Voting instructions are at https://docs.bisq.network/dao/phase-zero.html#how-to-vote.

Some of you will be voting for the first time and will need access. Just request it and I'll grant it.

Please don't forget that we are voting this time based on the [Natural delegation on DAO voting proposal](https://github.com/bisq-network/proposals/issues/34). Only vote `+1` on compensation requests you can evaluate and do know about, for all other compensation requests vote `0` to show your intention to delegate your vote.

Please complete your voting by EOD on Friday August 3rd.

Thanks all.

**Comment by ripcurlx** [comment]
This voting period is now complete, and the results are as follows:

10 contributors submitted 10 compensation requests.
No first-time compensation requests this time.
8 stakeholders voted (30 delegated votes based on https://github.com/bisq-network/proposals/issues/34).

Total compensation requested was 44,432 BSQ.
Total compensation received was 44,432 BSQ.

We have now completed 10 monthly voting rounds. In total, we have approved the creation of 432,831 new BSQ, or roughly 43,000 BSQ per month on average.
